#!/bin/bash

# TODO: This file is a work in progress

# extract vin
convert out.tiff -crop 400x1800+10+200 vin.jpg
# extract current principal
convert out.tiff -crop 200x1800+1500+200 amount.jpg

# pdf to tiff
convert -density 300 pdf/example.pdf -depth 8 -strip -background white -alpha off out/tiff/out.tiff
